### ISSUE TITLE
Errors are only shown to currently edited file

### ISSUE THREAD

**Issue by galman33** [rtorr/vscode-flow#16]
I think that since "Implement real time updates of flow diagnostics" (https://github.com/rtorr/vscode-flow/commit/08dfc4de93dc0913d9deae4fa78f643fc104f800) only errors of the currently edited file are shown. When I run flow manually from the command line, errors from the whole projects are shown too..

**Comment by rtorr** [comment]
Thanks for reporting, will take a look at this soon.

**Comment by tomitrescak** [comment]
I was using the "official" flow plugin from flowtype and found it really cumbersome and lazy. Your plugin is fantastic! It's fast and works in real time. Thanks for that! 

I can confirm the bug, it only shows error in the active file.

**Comment by rtorr** [comment]
Cool. Hoping to find some time this week.

**Comment by rtorr** [comment]
should be fixed in `vscode-flow@276.1.0`

**Comment by galman33** [comment]
Awesome! Good work :)

**Comment by tomitrescak** [comment]
Hmm, to me it still shows only errors in the active file ;( Running version 276.1.0

**Comment by rtorr** [comment]
@tomitrescak it should run flow check on first boot up. Can you close vscode, make sure flow is not running any where, then try it again?

**Comment by tomitrescak** [comment]
Yeah, I had man zombie processes running, but killing them made no difference ;(

![flow](https://cloud.githubusercontent.com/assets/2682705/17799610/5836c71e-661f-11e6-9ff1-01f10dffbda3.gif)

**Comment by galman33** [comment]
Happening to me to :(

**Comment by rtorr** [comment]
open to pull requests :D

**Comment by galman33** [comment]
There you go! https://github.com/rtorr/vscode-flow/pull/20
